CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userName" varchar NOT NULL,
  "userEmail" varchar UNIQUE NOT NULL,
  "userPassword" varchar NOT NULL,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "columns" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "columnName" varchar NOT NULL,
  "userId" integer NOT NULL,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cardName" varchar NOT NULL,
  "cardDescription" varchar NOT NULL,
  "isCompleted" bool NOT NULL DEFAULT false,
  "columnId" integer NOT NULL,
  "userId" integer NOT NULL,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "commentContent" varchar NOT NULL,
  "cardId" integer NOT NULL,
  "userId" integer NOT NULL,
  "createdAt" timestamp,
  "updatedAt" timestamp
);

ALTER TABLE "columns" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "cards" ADD FOREIGN KEY ("columnId") REFERENCES "columns" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("cardId") REFERENCES "cards" ("id");
