version: "3.9"
services:
   postgresql:
      image: postgres:latest
      container_name: postgres_trello1
      ports: -"5432:5432"
      environment:
         - POSTGRES_HOST=localhost
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=1234
         - POSTGRES_DATABASE=my_trello_db
      command: postgres
      restart: always

   redis:
      image: redis:latest
      container_name: redis_trello1
      ports:
         - "6379:6379"
# PORT = 5000
# POSTGRES_HOST=localhost
# POSTGRES_USER=postgres
# POSTGRES_DB=my_trello_db
# POSTGRES_PASSWORD=1234
# POSTGRES_PORT=5432

