import {
   BelongsTo,
   Column,
   DataType,
   ForeignKey,
   Model,
   Table,
} from "sequelize-typescript";
import { Users } from "./users.model";
import { Cards } from "./cards.model";

interface CommentCreationAttrs {
   comment_content: string;
   cardId: number;
   userId: number;
}

@Table({ tableName: "COMMENTS" })
export class Comments extends Model<Comments, CommentCreationAttrs> {
   @Column({ type: DataType.INTEGER, autoIncrement: true, primaryKey: true })
   id: number;

   @Column({ type: DataType.STRING, allowNull: false })
   commentContent: string;

   @ForeignKey(() => Cards)
   @Column({ type: DataType.INTEGER, allowNull: false })
   cardId: number;

   @BelongsTo(() => Cards)
   card: Cards;

   @ForeignKey(() => Users)
   @Column({ type: DataType.INTEGER, allowNull: false })
   userId: number;

   @BelongsTo(() => Users)
   author: Users;
}

// CREATE TABLE "comment" (
// 	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
// 	"comment_name" varchar NOT NULL,
// 	"card_id" integer NOT NULL,
// 	"created_at" timestamp,
// 	"updated_at" timestamp
//   );
